//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViamericasCareers.Application.ViamericasCareersServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DcJobs", Namespace="http://schemas.datacontract.org/2004/07/ViamericasCareers.WebServices.DataContrac" +
        "ts")]
    [System.SerializableAttribute()]
    public partial class DcJobs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DcCandidates", Namespace="http://schemas.datacontract.org/2004/07/ViamericasCareers.WebServices.DataContrac" +
        "ts")]
    [System.SerializableAttribute()]
    public partial class DcCandidates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobDescription {
            get {
                return this.JobDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDescriptionField, value) != true)) {
                    this.JobDescriptionField = value;
                    this.RaisePropertyChanged("JobDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((this.JobIdField.Equals(value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViamericasCareersServices.ICareers")]
    public interface ICareers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/ListJobs", ReplyAction="http://tempuri.org/ICareers/ListJobsResponse")]
        ViamericasCareers.Application.ViamericasCareersServices.DcJobs[] ListJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/ListJobs", ReplyAction="http://tempuri.org/ICareers/ListJobsResponse")]
        System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcJobs[]> ListJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/CandidatesList", ReplyAction="http://tempuri.org/ICareers/CandidatesListResponse")]
        ViamericasCareers.Application.ViamericasCareersServices.DcCandidates[] CandidatesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/CandidatesList", ReplyAction="http://tempuri.org/ICareers/CandidatesListResponse")]
        System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcCandidates[]> CandidatesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/AddCandidate", ReplyAction="http://tempuri.org/ICareers/AddCandidateResponse")]
        void AddCandidate(ViamericasCareers.Application.ViamericasCareersServices.DcCandidates newCandidate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/AddCandidate", ReplyAction="http://tempuri.org/ICareers/AddCandidateResponse")]
        System.Threading.Tasks.Task AddCandidateAsync(ViamericasCareers.Application.ViamericasCareersServices.DcCandidates newCandidate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/JobById", ReplyAction="http://tempuri.org/ICareers/JobByIdResponse")]
        ViamericasCareers.Application.ViamericasCareersServices.DcJobs JobById(long jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICareers/JobById", ReplyAction="http://tempuri.org/ICareers/JobByIdResponse")]
        System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcJobs> JobByIdAsync(long jobId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICareersChannel : ViamericasCareers.Application.ViamericasCareersServices.ICareers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CareersClient : System.ServiceModel.ClientBase<ViamericasCareers.Application.ViamericasCareersServices.ICareers>, ViamericasCareers.Application.ViamericasCareersServices.ICareers {
        
        public CareersClient() {
        }
        
        public CareersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CareersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CareersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CareersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ViamericasCareers.Application.ViamericasCareersServices.DcJobs[] ListJobs() {
            return base.Channel.ListJobs();
        }
        
        public System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcJobs[]> ListJobsAsync() {
            return base.Channel.ListJobsAsync();
        }
        
        public ViamericasCareers.Application.ViamericasCareersServices.DcCandidates[] CandidatesList() {
            return base.Channel.CandidatesList();
        }
        
        public System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcCandidates[]> CandidatesListAsync() {
            return base.Channel.CandidatesListAsync();
        }
        
        public void AddCandidate(ViamericasCareers.Application.ViamericasCareersServices.DcCandidates newCandidate) {
            base.Channel.AddCandidate(newCandidate);
        }
        
        public System.Threading.Tasks.Task AddCandidateAsync(ViamericasCareers.Application.ViamericasCareersServices.DcCandidates newCandidate) {
            return base.Channel.AddCandidateAsync(newCandidate);
        }
        
        public ViamericasCareers.Application.ViamericasCareersServices.DcJobs JobById(long jobId) {
            return base.Channel.JobById(jobId);
        }
        
        public System.Threading.Tasks.Task<ViamericasCareers.Application.ViamericasCareersServices.DcJobs> JobByIdAsync(long jobId) {
            return base.Channel.JobByIdAsync(jobId);
        }
    }
}
